# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fitnes_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #12343b")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 441, 111))
        self.frame.setStyleSheet(" background-color: #e1b382")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 30, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #12343b")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(370, 30, 51, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-jsvzMRKuzHMKYmrn.png"))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 490, 441, 111))
        self.frame_2.setStyleSheet(" background-color: #e1b382")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(50, 80, 51, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-E5ieymoQAkO.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(100, 80, 51, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-E5ieymoQAkO.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(150, 80, 51, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-E5ieymoQAkO.png"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(200, 80, 51, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-E5ieymoQAkO.png"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(250, 80, 51, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-E5ieymoQAkO.png"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(300, 80, 51, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-E5ieymoQAkO.png"))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(350, 80, 51, 31))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-E5ieymoQAkO.png"))
        self.label_11.setObjectName("label_11")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 47, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-hUlDW0e8ie44rfb.png"))
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(400, 60, 47, 51))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("./imgonline-com-ua-Resize-hUlDW0e8ie44rfb.png"))
        self.label_10.setObjectName("label_10")
        self.age = QtWidgets.QLineEdit(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(30, 150, 381, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.age.setFont(font)
        self.age.setStyleSheet("border: 2px solid #e1b382;\n"
"border-radius: 20;\n"
"color:white;")
        self.age.setAlignment(QtCore.Qt.AlignCenter)
        self.age.setObjectName("age")
        self.weight = QtWidgets.QLineEdit(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(30, 230, 381, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.weight.setFont(font)
        self.weight.setStyleSheet("border: 2px solid #e1b382;\n"
"border-radius: 20;\n"
"color:white;")
        self.weight.setAlignment(QtCore.Qt.AlignCenter)
        self.weight.setObjectName("weight")
        self.growth = QtWidgets.QLineEdit(self.centralwidget)
        self.growth.setGeometry(QtCore.QRect(30, 310, 381, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.growth.setFont(font)
        self.growth.setStyleSheet("border: 2px solid #e1b382;\n"
"border-radius: 20;\n"
"color:white;")
        self.growth.setAlignment(QtCore.Qt.AlignCenter)
        self.growth.setObjectName("growth")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 400, 381, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color:#12343b;\n"
"    background-color: #e1b382;\n"
"    border-radius: 20;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    border: 3px solid #12343b;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(450, 10, 541, 581))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: #e1b382;\n"
"color: #12343b ;")
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Фитнес тренер"))
        self.label.setText(_translate("MainWindow", "Фитнес тренер"))
        self.pushButton.setText(_translate("MainWindow", "Результат"))



if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
